import lldb
import time

def	fix(debugger, command, result, internal_dict):
	debugger.SetAsync(True)
	av = command.split()
	if len(av) == 3:
		debugger.HandleCommand("breakpoint set --name main")
		debugger.HandleCommand("proces launch")
		time.sleep(1)
		debugger.HandleCommand("watchpoint set variable count")
		debugger.HandleCommand("proces continue")
		time.sleep(1)
		debugger.HandleCommand("proces continue")
		time.sleep(1)
		debugger.GetSelectedTarget().GetProcess().PutSTDIN(str(av[0] + "\n"))
		time.sleep(1)
		debugger.HandleCommand("expression -- tab[0] = tab[1]")
		debugger.HandleCommand("proces continue")
		time.sleep(1)
		debugger.GetSelectedTarget().GetProcess().PutSTDIN(str(av[1] + "\n"))
		time.sleep(1)
		debugger.HandleCommand("expression int $tmp = tab[1]")
		debugger.HandleCommand("proces continue")
		time.sleep(1)
		debugger.GetSelectedTarget().GetProcess().PutSTDIN(str(av[2] + "\n"))
		time.sleep(1)
		debugger.HandleCommand("expression -- tab[2] = tab[1]; tab[1] = $tmp")
		debugger.HandleCommand("proces continue")
		time.sleep(1)
		debugger.HandleCommand("expression -- count = 0")
		debugger.HandleCommand("watchpoint delete 1")
		time.sleep(1)
		debugger.HandleCommand("breakpoint set -p 'tmp /= max'")
		debugger.HandleCommand("proces continue")
		time.sleep(1)
		debugger.HandleCommand("expression -- for(int i = 0; i < max; i++) tmp += min[i]")
		debugger.HandleCommand("breakpoint set -p 'return biggest'")
		debugger.HandleCommand("proces continue")
		time.sleep(1)
		debugger.HandleCommand("expression -- for(int i = 0; i < max; i++) if(biggest < min[i]) biggest = min[i]")
		debugger.HandleCommand("proces continue")
		time.sleep(2)
	else:
		print('usage: fix_source_cpp nbr1 nbr2 nbr3')

def	__lldb_init_module(debugger, internal_dict):
	debugger.HandleCommand('command script add -f fix_source_cpp.fix fix_source_cpp -h "fix the file source.cpp in 01-usage"')
